//A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.
//You are given a string S. You have to generate all the subsequences of the string S using a recursive approach (duplicates allowed)


function runProgram(input) {
    var input = input.split("\n");
    var N = +input[0];
    var str = input[1].trim();
    solve(N, str);

}
function solve(N, str) {

    function gs(str, newstr, position) {
        if (newstr.length > 0) {
            var bag = "";
            for (var j = 0; j < newstr.length; j++) {
                bag += newstr[j];
            }
            console.log(bag);
        }
        if (position == str.length) {
            return;
        }
        else {
            for (var i = position; i < str.length; i++) {
                newstr.push(str[i]);
                gs(str, newstr, i + 1);
                newstr.pop();
            }
        }
    }

    var newstr = [];
    gs(str, newstr, 0);

}





if (process.env.USER === "") {
    runProgram(``);
} else {
    process.stdin.resume();
    process.stdin.setEncoding("ascii");
    let read = "";
    process.stdin.on("data", function (input) {
        read += input;
    });
    process.stdin.on("end", function () {
        read = read.replace(/\n$/, "");
        read = read.replace(/\n$/, "");
        runProgram(read);
    });
    process.on("SIGINT", function () {
        read = read.replace(/\n$/, "");
        runProgram(read);
        process.exit(0);
    });
}